#!/bin/bash

select_branch () {
  cmdout=$(git branch | sed 's/*//g')
  branches=($cmdout)
  element_count=${#branches[@]}
  index=0
  echo "All branches:"
  while [ "$index" -lt "$element_count" ]
  do    # List all the elements in the array.
    echo "$index: ${branches[$index]}"
    let "index = $index + 1"
  done
  echo ""
  echo ">> Please input index of a branch:"
  read IDX
  branch=""
  if [ -n "$IDX" ]; then
    branch="${branches[$IDX]}"
  fi
}

COMMAND=""
while [ "$COMMAND" != "q" ]
do
  echo
  echo '~~~~~~~~~~~~~~~~~~~~'
  echo "Select a command:"
  echo "s. status"
  echo "d. diff"
  echo "a. add -Av"
  echo "f. fetch -v"
  echo "p. gpc"
  echo "u. pull -v"
  echo "b. branch"
  echo "o. checkout"
  echo "m. merge"
  echo "r. rebase"
  echo "c. commit -av"
  echo "v. archive"
  echo "x. launch gitx"
  echo "+. commit -av --amend"
  echo "-. branch -D"
  echo "q. exit"
  echo '~~~~~~~~~~~~~~~~~~~~'
  read -r -s -n 1 COMMAND
  echo ''
  if [ "$COMMAND" = "s" ] ; then
  echo ">> git status"
    git status
  elif [ "$COMMAND" = "d" ] ; then
  echo ">> git diff"
    git diff
  elif [ "$COMMAND" = "a" ] ; then
  echo ">> git add -Av"
    git add -Av
  elif [ "$COMMAND" = "f" ] ; then
  echo ">> git fetch -v"
    git fetch -v
  elif [ "$COMMAND" = "p" ] ; then
  echo ">> gpc"
    gpc
  elif [ "$COMMAND" = "u" ] ; then
  echo ">> git pull -v"
    git pull -v
  elif [ "$COMMAND" = "b" ] ; then
  echo ">> git branch"
    git branch
  elif [ "$COMMAND" = "o" ] ; then
    select_branch
    if [ -n "$branch" ]; then
      echo ">> git checkout \"$branch\""
      git checkout "$branch"
    fi
  elif [ "$COMMAND" = "m" ] ; then
    select_branch
    if [ -n "$branch" ]; then
      echo ">> git merge \"$branch\""
      git merge "$branch"
    fi
  elif [ "$COMMAND" = "r" ] ; then
    select_branch
    if [ -n "$branch" ]; then
      echo ">> git rebase \"$branch\""
      git rebase "$branch"
    fi
  elif [ "$COMMAND" = "c" ] ; then
    #echo ">> Please input a message: "
    #read MESSAGE
    #echo ">> git commit -av \"$MESSAGE\""
    git commit -av
    #m "$MESSAGE"
  elif [ "$COMMAND" = "v" ] ; then
    echo ">> git archive master | bzip2 > source-tree.tar.bz2"
    git archive master | bzip2 > ../source-tree.tar.bz2
  elif [ "$COMMAND" = "x" ] ; then
    echo ">> launching gitx ..."
    gitx
  elif [ "$COMMAND" = "+" ] ; then
    git commit -av --amend
  elif [ "$COMMAND" = "-" ] ; then
    select_branch
    if [ -n "$branch" ]; then
      echo ">> git branch -D \"$branch\""
      git branch -D "$branch"
    fi
  elif [ "$COMMAND" = "q" ] ; then
    exit 0
  else
    continue
  fi
done
